entornoP/applications/core/urls.py
from django.urls import path
from .views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

entornoP/applications/cursos/urls.py
from django.urls import path

from .views import (
    CursoListView,
    CursoDetailView,
    mis_cursos_view,
    inscribirse_curso_view,
    CursoCreateView,
    CursoUpdateView,
    ModuloCreateView,
    ModuloUpdateView,
    ContenidoCreateView,
    ContenidoUpdateView,
    modulo_toggle_publicacion_view,
    FormularioDetailView,
    editar_preguntas_formulario,
    crear_pregunta,
    editar_pregunta,
    ActualizarProgresoModulo,
    responder_formulario,
    crear_formulario,
    respuestas_formulario,
    resultado_formulario,
    reportes_desempeno,
    exportar_reporte_csv,
    curso_confirmar_eliminar,
    curso_eliminar,
    mis_notas_view,
    asignar_simulacion_modulo,
    iniciar_simulacion,
    crear_simulacion,

)


app_name = "cursos"

urlpatterns = [
    # cursos
    path("", CursoListView.as_view(), name="lista"),
    path("mis-cursos/", mis_cursos_view, name="mis_cursos"),
    path("mis-notas/", mis_notas_view, name="mis_notas"),
    path("crear/", CursoCreateView.as_view(), name="crear"),
    path("<int:pk>/", CursoDetailView.as_view(), name="detalle"),
    path("<int:pk>/editar/", CursoUpdateView.as_view(), name="editar"),
    path("<int:pk>/inscribirse/", inscribirse_curso_view, name="inscribirse"),
   
    path("curso/<int:pk>/confirmar-eliminar/",
         curso_confirmar_eliminar,
         name="curso_confirmar_eliminar"),

    path("curso/<int:pk>/eliminar/",
         curso_eliminar,
         name="curso_eliminar"),



    # módulos

    path(
        "<int:curso_pk>/modulos/crear/",
        ModuloCreateView.as_view(),
        name="modulo_crear",
    ),

    path(
        "modulos/<int:pk>/editar/",
        ModuloUpdateView.as_view(),
        name="modulo_editar",
    ),

    path(
        "modulos/<int:pk>/toggle-publicacion/",
        modulo_toggle_publicacion_view,
        name="modulo_toggle_publicacion",
    ),

    path(
        "modulos/<int:modulo_id>/progreso/",
        ActualizarProgresoModulo.as_view(),
        name="actualizar_progreso",
    ),
    path(
        "modulo/<int:modulo_id>/asignar-simulacion/",
        asignar_simulacion_modulo,
        name="asignar_simulacion_modulo",
    ),
 


    # contenidos
    path(
        "modulos/<int:modulo_pk>/contenidos/crear/",
        ContenidoCreateView.as_view(),
        name="contenido_crear",
    ),
    path(
        "contenidos/<int:pk>/editar/",
        ContenidoUpdateView.as_view(),
        name="contenido_editar",
    ),

    path(
        "simulacion/<int:simulacion_id>/iniciar/",
        iniciar_simulacion,
        name="iniciar_simulacion",
    ),

    # formularios (docente)

    path(
        "contenidos/<int:contenido_id>/formulario/crear/",
        crear_formulario,
        name="crear_formulario",
    ),

    path(
        "formularios/<int:pk>/",
        FormularioDetailView.as_view(),
        name="detalle_formulario",
    ),
    path(
        "formularios/<int:formulario_id>/preguntas/editar/",
        editar_preguntas_formulario,
        name="editar_preguntas_formulario",
    ),
    # mantener estos si sigues usando las vistas antiguas
    path(
        "formularios/<int:formulario_id>/preguntas/crear/",
        crear_pregunta,
        name="crear_pregunta",
    ),

    path(
        "pregunta/<int:pregunta_id>/editar/",
        editar_pregunta,
        name="editar_pregunta",
    ),

    # ver respuestas de un formulario (DOCENTE/ADMIN)
    path(
        "formularios/<int:formulario_id>/respuestas/",
        respuestas_formulario,
        name="respuestas_formulario",
    ),


    # responder formulario (alumno)
    path(
        "formularios/<int:formulario_id>/responder/",
        responder_formulario,
        name="responder_formulario",
    ),
    path(
        "formularios/<int:formulario_id>/resultado/",
        resultado_formulario,
        name="resultado_formulario",
    ),
   

    path(
        "reportes/",
        reportes_desempeno, 
        name="reportes_desempeno",
        ),

    path("reportes/csv/",
        exportar_reporte_csv, 
        name="exportar_reporte_csv",
        ),
        path(
            "modulo/<int:modulo_id>/crear-simulacion/",
            crear_simulacion,
            name="crear_simulacion",
            ),






    # si luego hacemos PDF:
    # path("reportes/pdf/", views.exportar_reporte_pdf, name="exportar_reporte_pdf"),



]

entornoP/applications/gestiondeusuarios/urls.py
from django.urls import path
from . import views

app_name = "gestiondeusuarios"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("registro/", views.registro_view, name="registro"),
    path("perfil/", views.editar_perfil, name="editar_perfil"),
    path("avatar/", views.elegir_avatar, name="elegir_avatar"),
]

entornoP/applications/tickets/urls.py
from django.urls import path
from . import views

app_name = "tickets"

urlpatterns = [
    path('nuevo/', views.crear_ticket, name='crear_ticket'),
    path('mis-tickets/', views.lista_tickets, name='lista_tickets'),
]

entornoP/rueba/urls.py
# rueba/urls.py
"""
URL configuration for rueba project.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Panel de administración
    path('admin/', admin.site.urls),

    # HOME (usa applications.core.urls → HomeView → home.html)
    path('', include('applications.core.urls')),

    # Usuarios (login, registro, logout, etc.)
    path('accounts/', include('applications.gestiondeusuarios.urls')),

    # Cursos
    path("cursos/", include("applications.cursos.urls")),

    # tickets
    path('tickets/', include('applications.tickets.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

entornoP/templates/partials/footer.html
{% load static %}
<!-- Footer Start -->
<div class="container-fluid position-relative overlay-top bg-dark text-white-50 py-5" style="margin-top: 90px;">
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-md-6 mb-5">

                <!-- LOGO + TEXTO (CORRECTO) -->
                <a href="#" class="navbar-brand ml-lg-3">
            <h1 class="m-0 text-uppercase text-white d-flex align-items-center">
                <img src="{% static 'img/Escudo-UCN-Full-blanco_trans.png' %}" 
                    alt="Escudo UCN" 
                    style="height: 40px;" 
                    class="me-2">
                EduSalud UCN
            </h1>
        </a>

                <p class="m-0">
                    Accusam nonumy clita sed rebum kasd eirmod elitr. Ipsum ea lorem at et diam est,
                    tempor rebum ipsum sit ea tempor stet et consetetur dolores. Justo stet diam ipsum
                    lorem vero clita diam.
                </p>

            </div>

            <div class="col-md-6 mb-5">
                <h3 class="text-white mb-4">Newsletter</h3>
                <div class="w-100">
                    <div class="input-group">
                        <input type="text" class="form-control border-light" style="padding: 30px;" placeholder="Your Email Address">
                        <div class="input-group-append">
                            <button class="btn btn-primary px-4">Sign Up</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4 mb-5">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>
                <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                <p><i class="fa fa-envelope mr-2"></i>info@example.com</p>
                <div class="d-flex justify-content-start mt-4">
                    <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-twitter"></i></a>
                    <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-facebook-f"></i></a>
                    <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-linkedin-in"></i></a>
                    <a class="text-white" href="#"><i class="fab fa-2x fa-instagram"></i></a>
                </div>
            </div>

            <div class="col-md-4 mb-5">
                <h3 class="text-white mb-4">Our Courses</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Web Design</a>
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Apps Design</a>
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Marketing</a>
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Research</a>
                    <a class="text-white-50" href="#"><i class="fa fa-angle-right mr-2"></i>SEO</a>
                </div>
            </div>

            <div class="col-md-4 mb-5">
                <h3 class="text-white mb-4">Quick Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Privacy Policy</a>
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Terms & Condition</a>
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Regular FAQs</a>
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Help & Support</a>
                    <a class="text-white-50" href="#"><i class="fa fa-angle-right mr-2"></i>Contact</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid bg-dark text-white-50 border-top py-4"
     style="border-color: rgba(256, 256, 256, .1) !important;">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-left mb-3 mb-md-0">
                <p class="m-0">
                    Copyright &copy;
                    <a class="text-white" href="#">Your Site Name</a>. All Rights Reserved.
                </p>
            </div>
            <div class="col-md-6 text-center text-md-right">
                <p class="m-0">
                    Designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    Distributed by <a class="text-white" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </p>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

entornoP/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg" style="background:#2f63c8; padding: 0.6rem 2rem;">

    <!-- Logo + texto EDUSALUD UCN -->
    <a href="{% url 'core:home' %}" class="navbar-brand d-flex align-items-center mb-0">
        <img src="{% static 'img/Escudo-UCN-Full-blanco_trans.png' %}"
             alt="UCN"
             style="height: 40px;"
             class="me-2">
        <span class="text-white fw-bold" style="font-size: 1.3rem;">EDUSALUD UCN</span>
    </a>

    {% if user.is_authenticated %}
    <!-- Botón hamburguesa -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
            aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-between" id="mainNavbar">
        <ul class="navbar-nav mx-auto">

            <!-- Home -->
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'core:home' %}">Home</a>
            </li>

            <!-- Cursos -->
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'cursos:lista' %}">Cursos</a>
            </li>

            <!-- Mis cursos (solo alumno) -->
            {% if user.role == 'student' or user.role == 'alumno' %}
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'cursos:mis_cursos' %}">Mis cursos</a>
            </li>
            {% endif %}

            <!-- Contacto con Crear Ticket adentro -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white"
                   href="#"
                   id="contactDropdown"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                    Contacto
                </a>
                <ul class="dropdown-menu" aria-labelledby="contactDropdown">
                    <li>
                        <a class="dropdown-item" href="{% url 'tickets:crear_ticket' %}">
                            Crear ticket de soporte
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="mailto:soporte@ucn.cl">
                            Email soporte
                        </a>
                    </li>
                </ul>
            </li>

        </ul>

        <!-- Botón login/logout -->
        <div class="d-flex">
            {% if user.is_authenticated and user.avatar and user.avatar.imagen %}
                <img src="{{ user.avatar.imagen.url }}"
                     alt="Avatar"
                     class="rounded-circle"
                     style="width: 32px; height: 32px; object-fit: cover; margin-right: 8px;">
            {% endif %}

            <a href="{% url 'gestiondeusuarios:logout' %}"
               class="btn btn-outline-light btn-sm">
                Cerrar sesión
            </a>
        </div>
    </div>
    {% endif %}
</nav>